# Generated by Django 5.2 on 2025-04-23 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
