# Generated by Django 5.2 on 2025-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='agent_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
