# Generated by Django 5.2 on 2025-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0002_alter_topup_agent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='agent_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
