# Generated by Django 5.2 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0003_alter_topup_agent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(choices=[('requested', 'REQUESTED'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=255),
        ),
    ]
