# Generated by Django 5.2 on 2025-04-15 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(error_messages={'unique': 'Ce mail existe deja !'}, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Client')], default='customer', max_length=20)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_uuid', models.UUIDField(default=uuid.uuid4)),
                ('card', models.FileField(blank=True, null=True, upload_to='cards/')),
                ('card_exp_date', models.DateTimeField(blank=True, null=True)),
                ('sponsor_email', models.EmailField(blank=True, max_length=191, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('currency', models.CharField(default='CAD', max_length=191)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shOther', models.BooleanField(default=False)),
                ('shBilling', models.BooleanField(default=False)),
                ('shCarrier', models.BooleanField(default=False)),
                ('api_token', models.CharField(blank=True, max_length=191, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=191, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified_at', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
