# Generated by Django 5.2 on 2025-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Client'), ('agent', 'Agent')], default='customer', max_length=20),
        ),
    ]
