# Generated by Django 5.2 on 2025-04-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shBilling',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shCarrier',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shOther',
        ),
    ]
