# Generated by Django 5.2 on 2025-04-19 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='beneficiaries',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Client'), ('agent', 'Agent'), ('beneficiary', 'Bénéficiaire')], default='customer', max_length=20),
        ),
    ]
