# Generated by Django 5.2 on 2025-04-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_beneficiaries_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='beneficiaries',
        ),
    ]
