# Generated by Django 5.2 on 2025-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_card_customuser_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(default=224, error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.'}, max_length=5),
            preserve_default=False,
        ),
    ]
