# Generated by Django 5.2 on 2025-04-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
    ]
