# Generated by Django 5.2 on 2025-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_customuser_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(error_messages={'blank': 'Le pays ne peut pas être vide !', 'null': 'Le pays ne peut pas être vide !', 'required': 'Le numero de téléphone est requis !', 'unique': 'Ce pays existe deja !'}, max_length=50),
        ),
    ]
