# Generated by Django 5.2 on 2025-04-23 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_beneficiary_active_beneficiary_id_card_and_more'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='beneficiary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_statements', to='beneficiary.beneficiary'),
            preserve_default=False,
        ),
    ]
