# Generated by Django 5.2 on 2025-04-23 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0004_beneficiary_active_beneficiary_id_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('cashout_location', models.CharField(max_length=255)),
                ('payout_option', models.CharField(max_length=255)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sender_currency', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('recipient_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('agent_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(max_length=255)),
                ('transaction_completion_date', models.DateTimeField()),
                ('agent_start_username', models.CharField(max_length=255)),
                ('agent_completion_username', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=255, null=True)),
                ('remittance_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_beneficiaries', to='beneficiary.beneficiary')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
