# Generated by Django 5.2 on 2025-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='agent_completion_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='agent_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='agent_start_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='partner_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='transaction_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
