# Generated by Django 5.2 on 2025-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
    ]
       
