# Generated by Django 5.2 on 2025-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_fees_from_c_remove_fees_to_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='from_c',
            new_name='from_amount',
        ),
        migrations.RenameField(
            model_name='fees',
            old_name='to_c',
            new_name='to_amount',
        ),
    ]
