# Generated by Django 5.2 on 2025-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_rename_from_c_fees_from_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
