# Generated by Django 5.2 on 2025-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_currency', models.CharField(max_length=3, verbose_name='Devise source')),
                ('dest_currency', models.CharField(max_length=3, verbose_name='Devise de destination')),
                ('ratio', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Taux de change')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
    ]
