# Generated by Django 5.2 on 2025-04-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrate',
            old_name='dest_currency',
            new_name='dst_currency',
        ),
    ]
