# Generated by Django 5.2 on 2025-04-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_beneficiary_beneficiary_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.', 'unique': 'Ce numéro de téléphone est déjà utilisé.'}, max_length=13, unique=True),
        ),
    ]
