# Generated by Django 5.2 on 2025-04-23 19:46

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_alter_beneficiary_phone_number'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='beneficiary',
        #     name='active',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddField(
        #     model_name='beneficiary',
        #     name='id_card',
        #     field=models.CharField(default=None, max_length=191),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='beneficiary',
            name='id_exp_date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
