# Generated by Django 5.2 on 2025-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_beneficiary_active_beneficiary_id_card_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='beneficiary',
        #     name='active',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddField(
        #     model_name='beneficiary',
        #     name='id_card',
        #     field=models.CharField(default=None, max_length=191),
        #     preserve_default=False,
        # ),
    ]
