# Generated by Django 5.2 on 2025-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0006_beneficiary_active_beneficiary_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='id_exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
