# Generated by Django 5.2 on 2025-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_alter_beneficiary_id_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='country_code',
            field=models.CharField(default=224, max_length=5),
            preserve_default=False,
        ),
    ]
