# Generated by Django 5.2 on 2025-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_beneficiary_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='country_code',
            field=models.CharField(error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.'}, max_length=5),
        ),
    ]
