# Generated by Django 5.2 on 2025-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_alter_beneficiary_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='country_currency',
            field=models.CharField(default='GNF', error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.'}, max_length=5),
        ),
    ]
