# Generated by Django 5.2 on 2025-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0010_beneficiary_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'Ce champ ne peut pas être vide.', 'null': 'Ce champ ne peut pas être nul.'}, max_length=13),
        ),
    ]
